---
- hosts: localhost
  collections:
    - community.kubernetes
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition: "{{ lookup('file','file/python-service.yaml') }}"
        validate_certs: no
        namespace: default
    - name: Deploy the Ingress
      k8s:
        state: present
        definition: "{{ lookup('file','file/python-ingress.yaml') }}"
        validate_certs: no
        namespace: default
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        definition:  "{{ lookup('file','file/python-deployment.yaml') }}"
